# Generated by Django 2.2.6 on 2020-05-07 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='待补充', max_length=20, verbose_name='姓名')),
                ('Sex', models.IntegerField(default=0, verbose_name='性别')),
                ('Birthday', models.CharField(default='待补充', max_length=20, verbose_name='生日')),
                ('Degree', models.IntegerField(default=0, verbose_name='学历')),
                ('NativePlace', models.CharField(default='待补充', max_length=10, verbose_name='籍贯')),
                ('Address', models.CharField(default='待补充', max_length=30, verbose_name='地址')),
                ('Tel', models.CharField(default='待补充', max_length=15, verbose_name='电话')),
                ('WorkYears', models.IntegerField(default=0, verbose_name='工龄')),
                ('Salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
